import { Suspense } from "react";
import Loading from "../components/loading";

export const metadata = {
  title: "Armoo Design - Notes",
  description: "Generated by create next app",
};

function NotesLayout({ children }) {
  return <Suspense fallback={<Loading />}>{children}</Suspense>;
}

export default NotesLayout;
