import { Suspense } from "react";
import Loading from "../components/loading";

export const metadata = {
  title: "Armoo Design - About",
  description: "Generated by create next app",
};

function AboutLayout({ children }) {
  return <Suspense fallback={<Loading />}>{children}</Suspense>;
}

export default AboutLayout;
