export const metadata = {
  title: "Armoo Design - Project",
  description: "Generated by create next app",
};

export default function Project() {
  return (
    <div className="project-page bg-red-50 text-ownBlack w-full h-full flex justify-center items-center">
      Project
    </div>
  );
}
