import { Poppins } from "next/font/google";
import Header from "./components/header";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400"],
});

export const metadata = {
  title: "Armoo Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} w-screen h-screen`}>
        <Header />
        <div className="w-screen h-screen p-4 overflow-hidden relative">
          <main className="bg-teal-50 w-full h-full rounded-3xl overflow-hidden">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
